live_config_reload = true

[env]
TERM = "tmux-256color"

[shell]
program = "/bin/zsh"
args = [
	"-c",
	"tmux new-session -d 'fastfetch && exec $SHELL'; tmux attach-session -d",
]

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 0
y = 0

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[selection]
# This string contains all characters that are used as separators for
# "semantic words" in Alacritty.
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard = true
